eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from home.models import Article
import random
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.template import RequestContext

from django.conf.urls import (
    handler400, handler403, handler404, handler500
)



handler404 = 'home.views.page_not_found'



RANDOM_TEXT = """
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias, quibusdam? Adipisci aut consequuntur
    dolore doloremque dolorum enim eum fugiat magni maxime minus neque non officiis optio perspiciatis quam qui ratione
    saepe sed sequi sit, tempore vitae voluptas. Animi architecto, dolorem eos excepturi fugit maxime necessitatibus
    quaerat qui! Ad animi aut cum delectus deserunt dolor earum eius eligendi error est, et excepturi illo impedit
    ipsum, minus nesciunt quia quisquam reiciendis! Consequuntur maiores necessitatibus tempore? A alias autem
    consequuntur corporis cum cumque cupiditate dolorum eveniet harum inventore, iure modi omnis perspiciatis, quas
    quasi qui quibusdam rem sapiente sed similique sunt veritatis.
""".split()


def generate_articles(request):
    for i in range(1000):
        new_article = Article()
        new_article.title = ' '.join(random.sample(RANDOM_TEXT, 3))
        new_article.text = ' '.join(random.sample(RANDOM_TEXT, 74))
        new_article.price = random.randrange(578)
        new_article.save()
    return HttpResponse('Articles done!')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('generate_articles', generate_articles),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users'))
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('article-detail/<int:id_article>' , views.detail_article),
    path('calc/' , views.calc),
    path('examples/' , views.examples),
    path('add-article/' , views.add_article),
]

users/urls.py
from django.urls import path
from . import views
from . import auth_views
from . import session_views

app_name = "users"

urlpatterns = [
    path('cabinet-route-asdasd/', views.cabinet, name='cabinet'),
    path('all-books-user/', views.all_books, name='all_books'),
    path('write_book/', views.write_book, name='write_book'),
    path('books/', views.books, name='books'),
    path('search/', views.search, name='search'),
    path('my_order/', views.my_order, name='my_order'),
]

x = [
    path('register', auth_views.register, name='register'),
    path('login', auth_views.login, name='login'),
    path('logout', auth_views.logout, name='logout'),
]

session_urls = [
    path('add_to_session/<int:book_id>/', session_views.add_to_session, name='add_to_session'),
    path('bucket', session_views.bucket, name='bucket'),
    path('delete_from_bucket/<int:pk>/', session_views.delete_from_bucket, name='delete_from_bucket'),
    path('approve_order', session_views.approve_order, name='approve_order'),
]

urlpatterns += x
urlpatterns += session_urls

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserAuthor(models.Model):
    TYPE_USER_VIEW = (
        ('fio', 'ФИО'),
        ('pseudo_name', 'Псевдоним'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=1500, verbose_name='Биография')
    type_view = models.CharField(choices=TYPE_USER_VIEW, max_length=50, verbose_name='Тип представления0')
    pseudoname = models.CharField(max_length=150, verbose_name='Псевдоним', blank=True, null=True)

    def __str__(self):
        return str(self.user)

    def get_name(self):
        if self:
            if self.type_view == 'fio':
                return '{} {}'.format(self.user.first_name, self.user.last_name)
            elif self.type_view == 'pseudo_name':
                return self.pseudoname or 'anonim'


class Book(models.Model):
    TYPE_GENRE = (
        ('comedy', 'Комедия'),
        ('drama', 'Драма'),
        ('fantastic', 'Фантастик'),
    )
    title = models.CharField(max_length=500, verbose_name='Название')
    lead = models.TextField(max_length=1500, verbose_name='Краткое описание книги')
    genre = models.CharField(choices=TYPE_GENRE, max_length=50, verbose_name='Жанр')
    rate = models.IntegerField(default=0, verbose_name='Рейтинг')
    author = models.ForeignKey(UserAuthor, on_delete=models.SET_NULL, blank=True, null=True)
    price = models.IntegerField(default=100, verbose_name='Цена')

    def __str__(self):
        return self.title


class Order(models.Model):
    first_name = models.CharField(max_length=255, verbose_name='Имя'
                                  , blank=True, null=True, default='')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия'
                                 , blank=True, null=True, default='')
    middle_name = models.CharField(max_length=255, verbose_name='Отчество'
                                   , blank=True, null=True, default='')
    email = models.EmailField(max_length=255, verbose_name='E-mail')
    phone_number = models.CharField(max_length=13, verbose_name='Номер телефона')
    books = models.ManyToManyField(Book)
    total_price = models.FloatField(blank=True, null=True, default=0)
    msg = models.TextField(max_length=6000, verbose_name='Комментарий к заказу', blank=True, null=True, default='')

    def __str__(self):
        return 'Заказ № {}. От {} {} {}'.format(self.id, self.first_name, self.last_name, self.phone_number)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserAuthor, Book, Order


class SingUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=150, required=False, label='Имя')
    second_name = forms.CharField(max_length=150, required=False, label='Фамилия')
    email = forms.EmailField(max_length=200, required=False)

    def save(self, *args, **kwargs):
        data = self.cleaned_data
        django_user = User.objects.create_user(
            username=data['username'],
            password=data['password1'],
            first_name=data['first_name'],
            last_name=data['second_name'],
            email=data['email']
        )
        UserAuthor.objects.create(user=django_user)
        return django_user


class UserAuthorForm(forms.ModelForm):
    class Meta:
        model = UserAuthor
        exclude = 'user',


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ('author',)

    def save(self, *args, **kwargs):
        current_user = kwargs.pop('author')
        if current_user:
            self.instance.author = current_user
            self.instance.save()


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('books', 'total_price')

    def save(self, *args, **kwargs):
        print('custom save!!!!')
        new_order = Order(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            middle_name=self.cleaned_data['middle_name'],
            email=self.cleaned_data['email'],
            phone_number=self.cleaned_data['phone_number'],
            total_price=kwargs.get('total_price', 0),
            msg=self.cleaned_data['msg']
        )
        new_order.save()
        for book in kwargs['books']:
            new_order.books.add(book.id)

users/views.py
from django.shortcuts import render, redirect
from .models import UserAuthor, Book, Order
from .forms import UserAuthorForm, BookForm


# Create your views here.


def cabinet(request):
    ctx = {}
    ctx['cabinet_tab'] = 'main'
    if request.user.is_authenticated:
        author = UserAuthor.objects.get(user_id=request.user.id)
        form = UserAuthorForm(instance=author)
        if request.method == 'POST':
            form = UserAuthorForm(instance=author, data=request.POST)
            if form.is_valid():
                form.save()
                ctx['saved'] = 1
                form = UserAuthorForm(instance=author)
            else:
                ctx['form'] = form
                ctx['saved'] = 2

        ctx['form'] = form
        return render(request, 'users/cabinet/main.html', ctx)
    else:
        return redirect('users:login')


def all_books(request):
    ctx = {}
    ctx['cabinet_tab'] = 'all_books'
    current_author = UserAuthor.objects.get(user_id=request.user.id)
    all_books = Book.objects.filter(author=current_author)
    ctx['all_books'] = all_books
    return render(request, 'users/cabinet/all_books.html', ctx)


def write_book(request):
    ctx = {}
    ctx['cabinet_tab'] = 'create_book'
    ctx['form'] = BookForm()
    if request.method == 'POST':
        form = BookForm(data=request.POST)
        current_author = UserAuthor.objects.get(user_id=request.user.id)
        if form.is_valid():
            form.save(author=current_author)
    return render(request, 'users/cabinet/write_book.html', ctx)


def books(request):
    ctx = {}
    ctx['all_books'] = Book.objects.all().order_by('-id')
    return render(request, 'users/books.html', ctx)


def search(request):
    ctx = {}
    user_email = request.GET.get('email')
    ctx['email'] = user_email
    all_orders = Order.objects.filter(email=user_email)
    ctx['all_orders'] = all_orders
    return render(request, 'users/search.html', ctx)


def my_order(request):
    ctx = {}
    all_orders = Order.objects.all()
    current_author = UserAuthor.objects.get(user_id=request.user.id)
    list_orders = []
    for order in all_orders:
        all_books = order.books.all()
        if all_books:
            all_books_by_current_author = [book for book in all_books if book.author == current_author]
            if all_books_by_current_author:
                order_obj = {
                    'order': order,
                    'books': all_books_by_current_author
                }
                list_orders.append(order_obj)
    total_sum_books = sum([book.price
                           for order in list_orders
                                for book in order['books']
                           ])
    commision = total_sum_books * 0.05  # percent from platform
    clean_price = total_sum_books - commision
    ctx['cabinet_tab'] = 'my_order'
    ctx['list_orders'] = list_orders
    ctx['commision'] = commision
    ctx['clean_price'] = clean_price
    return render(request, 'users/cabinet/my_order.html', ctx)

templates/users/cabinet/all_books.html
{% extends 'users/cabinet/main.html' %}

{% block cabinet %}
<h1>All books!</h1>
<a href="{% url 'users:write_book' %}" class="btn btn-link">Выдать книгу</a>


<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">ID</th>
        <th scope="col">title</th>
        <th scope="col">lead</th>
        <th scope="col">genre</th>
        <th scope="col">rate</th>
        <th scope="col">price , грн</th>
    </tr>
    </thead>
    <tbody>
    {% for book in all_books %}
    <tr>
        <th scope="row">{{ book.id }}</th>
        <td>{{ book.title}}</td>
        <td>{{book.lead}}</td>
        <td>{{book.get_genre_display}}</td>
        <td>{{book.rate}}</td>
        <td>{{book.price}}</td>
    </tr>

    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/users/cabinet/main.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Добро пожаловать {{request.user}} !</h1>

<div class="row">
    <div class="col-md-3">
        <nav class="nav flex-column">
            <a class="nav-link {% if cabinet_tab == 'main' %} btn btn-success {% endif %}" href="{% url 'users:cabinet' %}">Личная информация</a>
            <a class="nav-link {% if cabinet_tab == 'all_books' %} btn btn-success {% endif %}" href="{% url 'users:all_books' %}">Все книги</a>
            <a class="nav-link {% if cabinet_tab == 'create_book' %} btn btn-success {% endif %}"  href="{% url 'users:write_book' %}">Выдать книгу</a>
            <a class="nav-link {% if cabinet_tab == 'my_order' %} btn btn-success {% endif %}" href="{% url 'users:my_order' %}">Заказы</a>
        </nav>
    </div>
    <div class="col-md-9">
        {% block cabinet %}
            {% if saved  == 1%}
            <p class="alert alert-success">Данные успешно сохранены</p>
            {% elif  saved == 2 %}
            <p class="alert alert-danger">Пожалуйста исправьте ошибки</p>
            {% endif %}
            <form action="{% url 'users:cabinet' %}" method="post">
                {% csrf_token %}
                {% for f in form %}

                {{f | as_crispy_field}}
                {% endfor %}
                <button class="btn btn-success">Save</button>
            </form>
        {% endblock %}
    </div>
</div>

{% endblock %}

templates/users/cabinet/my_order.html
{% extends 'users/cabinet/main.html' %}
{% block cabinet %}

<h1>все заказы на ваши книги</h1>

{% for order in list_orders %}
<p>{{ order.order }}</p>
<ul>
    {% for book_order in order.books %}
    <li>{{book_order.title}} : <b>{{ book_order.price }} грн </b></li>
    {% endfor %}
</ul>
{% endfor %}
<div class="row">
    <div class="col-md-6">
        <p class="alert alert-success">
            Всего вы заработали (с учетом комиссии платформы) <b>{{ clean_price }}</b> грн
        </p>
    </div>
    <div class="col-md-6">
        <p class="alert alert-warning">
            Комиссия платформы <b>{{ commision }}</b> грн
        </p>
    </div>
</div>
{% endblock %}

templates/users/cabinet/write_book.html
{% extends 'users/cabinet/main.html' %}

{% load crispy_forms_tags %}

{% block cabinet %}
<h1>Book create!</h1>
<form action="{% url 'users:write_book' %}" method="post">
    {% csrf_token %}
    {% for f in form %}
    {{f | as_crispy_field}}
    {% endfor %}
    <button class="btn btn-success">Сохранить</button>
</form>
{% endblock %}