books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books_home, name='main'),
    path('book-detail/<int:pk>/', views.book_detail , name='book_detail'),
    path('author/<int:pk>/', views.author_detail),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from home.models import Article
import random
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.template import RequestContext

from django.conf.urls import (
    handler400, handler403, handler404, handler500
)



handler404 = 'home.views.page_not_found'



RANDOM_TEXT = """
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias, quibusdam? Adipisci aut consequuntur
    dolore doloremque dolorum enim eum fugiat magni maxime minus neque non officiis optio perspiciatis quam qui ratione
    saepe sed sequi sit, tempore vitae voluptas. Animi architecto, dolorem eos excepturi fugit maxime necessitatibus
    quaerat qui! Ad animi aut cum delectus deserunt dolor earum eius eligendi error est, et excepturi illo impedit
    ipsum, minus nesciunt quia quisquam reiciendis! Consequuntur maiores necessitatibus tempore? A alias autem
    consequuntur corporis cum cumque cupiditate dolorum eveniet harum inventore, iure modi omnis perspiciatis, quas
    quasi qui quibusdam rem sapiente sed similique sunt veritatis.
""".split()


def generate_articles(request):
    for i in range(1000):
        new_article = Article()
        new_article.title = ' '.join(random.sample(RANDOM_TEXT, 3))
        new_article.text = ' '.join(random.sample(RANDOM_TEXT, 74))
        new_article.price = random.randrange(578)
        new_article.save()
    return HttpResponse('Articles done!')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('generate_articles', generate_articles),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users'))
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('article-detail/<int:id_article>' , views.detail_article),
    path('calc/' , views.calc),
    path('examples/' , views.examples),
    path('add-article/' , views.add_article),
]

users/urls.py
from django.urls import path
from . import views
from . import auth_views
from . import session_views

app_name = "users"

urlpatterns = [
    path('cabinet-route-asdasd/', views.cabinet, name='cabinet'),
    path('all-books-user/', views.all_books, name='all_books'),
    path('write_book/', views.write_book, name='write_book'),
    path('books/', views.books, name='books'),
    path('search/', views.search, name='search'),
    path('my_order/', views.my_order, name='my_order'),
]

x = [
    path('register', auth_views.register, name='register'),
    path('login', auth_views.login, name='login'),
    path('logout', auth_views.logout, name='logout'),
]

session_urls = [
    path('add_to_session/<int:book_id>/', session_views.add_to_session, name='add_to_session'),
    path('bucket', session_views.bucket, name='bucket'),
    path('delete_from_bucket/<int:pk>/', session_views.delete_from_bucket, name='delete_from_bucket'),
    path('approve_order', session_views.approve_order, name='approve_order'),
]

urlpatterns += x
urlpatterns += session_urls

templates/footer.html
<footer>
    This is included footer
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/examples">Examples</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:books' %}">Купить книгу</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'books:main' %}">все книги</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        {% if request.user.is_authenticated %}
        <a href="{% url 'users:logout' %}" class="btn btn-danger">выйти ({{ request.user.username }})</a>

        {% else %}
        <a class="btn btn-primary" href="{% url 'users:register' %}">Регистрация</a>
        <a class="btn btn-success" href="{% url 'users:login' %}">Вход</a>
        {% endif %}
        <a href="{% url 'users:cabinet' %}" class="btn btn-info">Зайти в кабинет</a>
        <a href="{% url 'users:bucket' %}" class="btn btn-warning">корзина({{ request.session.books_bucket | length }})</a>
        <form action="{% url 'users:search' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="email" placeholder="Get order by email" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>

{% include 'header.html' %}


<div class="container">
    {% block content %}

    {% endblock %}
</div>

{% block x %}
{% endblock x %}

{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

{% block js %}
{% endblock js %}
</body>
</html>