books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books_home, name='main'),
    path('book-detail/<int:pk>/', views.book_detail , name='book_detail'),
    path('author/<int:pk>/', views.author_detail),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from home.models import Article
import random
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.template import RequestContext

from django.conf.urls import (
    handler400, handler403, handler404, handler500
)



handler404 = 'home.views.page_not_found'



RANDOM_TEXT = """
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias, quibusdam? Adipisci aut consequuntur
    dolore doloremque dolorum enim eum fugiat magni maxime minus neque non officiis optio perspiciatis quam qui ratione
    saepe sed sequi sit, tempore vitae voluptas. Animi architecto, dolorem eos excepturi fugit maxime necessitatibus
    quaerat qui! Ad animi aut cum delectus deserunt dolor earum eius eligendi error est, et excepturi illo impedit
    ipsum, minus nesciunt quia quisquam reiciendis! Consequuntur maiores necessitatibus tempore? A alias autem
    consequuntur corporis cum cumque cupiditate dolorum eveniet harum inventore, iure modi omnis perspiciatis, quas
    quasi qui quibusdam rem sapiente sed similique sunt veritatis.
""".split()


def generate_articles(request):
    for i in range(1000):
        new_article = Article()
        new_article.title = ' '.join(random.sample(RANDOM_TEXT, 3))
        new_article.text = ' '.join(random.sample(RANDOM_TEXT, 74))
        new_article.price = random.randrange(578)
        new_article.save()
    return HttpResponse('Articles done!')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('generate_articles', generate_articles),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users'))
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('article-detail/<int:id_article>' , views.detail_article),
    path('calc/' , views.calc),
    path('examples/' , views.examples),
    path('add-article/' , views.add_article),
]

users/urls.py
from django.urls import path
from . import views
from . import auth_views
from . import session_views

app_name = "users"

urlpatterns = [
    path('cabinet-route-asdasd/', views.cabinet, name='cabinet'),
    path('all-books-user/', views.all_books, name='all_books'),
    path('write_book/', views.write_book, name='write_book'),
    path('books/', views.books, name='books'),
    path('search/', views.search, name='search'),
    path('my_order/', views.my_order, name='my_order'),
]

x = [
    path('register', auth_views.register, name='register'),
    path('login', auth_views.login, name='login'),
    path('logout', auth_views.logout, name='logout'),
]

session_urls = [
    path('add_to_session/<int:book_id>/', session_views.add_to_session, name='add_to_session'),
    path('bucket', session_views.bucket, name='bucket'),
    path('delete_from_bucket/<int:pk>/', session_views.delete_from_bucket, name='delete_from_bucket'),
    path('approve_order', session_views.approve_order, name='approve_order'),
]

urlpatterns += x
urlpatterns += session_urls

books/models.py
from django.db import models


# Create your models here.


class Author(models.Model):
    TYPE_GENRE = (
        ('comedy', 'Комедия'),
        ('drama', 'Драма'),
        ('fantastic', 'Фантастик'),
    )

    name = models.CharField(max_length=255, verbose_name='Имя автора')
    surname = models.CharField(max_length=255, verbose_name='Фамилия автора')
    genre = models.CharField(choices=TYPE_GENRE , max_length = len('fantastic'))

    def __str__(self):
        return '{} {}: {}'.format(
            self.name, self.surname, self.genre
        )

    def get_full_name(self):
        return '{} {}'.format(self.name.capitalize() , self.surname.capitalize())

    def get_books(self):
        return Book.objects.filter(author=self)

    def get_total_price(self):
        all_books  = self.get_books()
        total_price = 0
        sale_price  = 0
        for book in all_books:
            if book.is_sale:
                total_price += book.new_price
                sale_price += book.price  - book.new_price
            else:
                total_price += book.price
        return {
            'total_price': total_price,
            'sale_price': sale_price,
        }


class Book(models.Model):
    author  = models.ForeignKey(Author,on_delete=models.CASCADE)
    title = models.CharField(max_length=500, verbose_name="Заголовок книги")
    price = models.IntegerField()
    is_sale = models.BooleanField(default=False)
    new_price = models.IntegerField(blank=True, null=True)
    desc = models.TextField(verbose_name="Описание книги" , max_length=1500)

    def __str__(self):
        return '{} {}'.format(self.title ,self.price)

    def calc_economy(self):
        if self.is_sale:
            return {
                'money': self.price - self.new_price,
                'percent': round((1 - self.new_price / self.price) * 100 , 2)
            }

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserAuthor(models.Model):
    TYPE_USER_VIEW = (
        ('fio', 'ФИО'),
        ('pseudo_name', 'Псевдоним'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=1500, verbose_name='Биография')
    type_view = models.CharField(choices=TYPE_USER_VIEW, max_length=50, verbose_name='Тип представления0')
    pseudoname = models.CharField(max_length=150, verbose_name='Псевдоним', blank=True, null=True)

    def __str__(self):
        return str(self.user)

    def get_name(self):
        if self:
            if self.type_view == 'fio':
                return '{} {}'.format(self.user.first_name, self.user.last_name)
            elif self.type_view == 'pseudo_name':
                return self.pseudoname or 'anonim'


class Book(models.Model):
    TYPE_GENRE = (
        ('comedy', 'Комедия'),
        ('drama', 'Драма'),
        ('fantastic', 'Фантастик'),
    )
    title = models.CharField(max_length=500, verbose_name='Название')
    lead = models.TextField(max_length=1500, verbose_name='Краткое описание книги')
    genre = models.CharField(choices=TYPE_GENRE, max_length=50, verbose_name='Жанр')
    rate = models.IntegerField(default=0, verbose_name='Рейтинг')
    author = models.ForeignKey(UserAuthor, on_delete=models.SET_NULL, blank=True, null=True)
    price = models.IntegerField(default=100, verbose_name='Цена')

    def __str__(self):
        return self.title


class Order(models.Model):
    first_name = models.CharField(max_length=255, verbose_name='Имя'
                                  , blank=True, null=True, default='')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия'
                                 , blank=True, null=True, default='')
    middle_name = models.CharField(max_length=255, verbose_name='Отчество'
                                   , blank=True, null=True, default='')
    email = models.EmailField(max_length=255, verbose_name='E-mail')
    phone_number = models.CharField(max_length=13, verbose_name='Номер телефона')
    books = models.ManyToManyField(Book)
    total_price = models.FloatField(blank=True, null=True, default=0)
    msg = models.TextField(max_length=6000, verbose_name='Комментарий к заказу', blank=True, null=True, default='')

    def __str__(self):
        return 'Заказ № {}. От {} {} {}'.format(self.id, self.first_name, self.last_name, self.phone_number)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserAuthor, Book, Order


class SingUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=150, required=False, label='Имя')
    second_name = forms.CharField(max_length=150, required=False, label='Фамилия')
    email = forms.EmailField(max_length=200, required=False)

    def save(self, *args, **kwargs):
        data = self.cleaned_data
        django_user = User.objects.create_user(
            username=data['username'],
            password=data['password1'],
            first_name=data['first_name'],
            last_name=data['second_name'],
            email=data['email']
        )
        UserAuthor.objects.create(user=django_user)
        return django_user


class UserAuthorForm(forms.ModelForm):
    class Meta:
        model = UserAuthor
        exclude = 'user',


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ('author',)

    def save(self, *args, **kwargs):
        current_user = kwargs.pop('author')
        if current_user:
            self.instance.author = current_user
            self.instance.save()


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('books', 'total_price')

    def save(self, *args, **kwargs):
        print('custom save!!!!')
        new_order = Order(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            middle_name=self.cleaned_data['middle_name'],
            email=self.cleaned_data['email'],
            phone_number=self.cleaned_data['phone_number'],
            total_price=kwargs.get('total_price', 0),
            msg=self.cleaned_data['msg']
        )
        new_order.save()
        for book in kwargs['books']:
            new_order.books.add(book.id)

books/views.py
from django.shortcuts import render
from .models import Book , Author
# Create your views here.


def books_home(request):
    ctx  = {}
    ctx['active_tab'] = 'books'
    ctx['all_books'] = Book.objects.all()
    return render(request , 'books/home.html' , ctx)


def book_detail(request , pk):
    ctx  = {}
    ctx['active_tab'] = 'books'
    ctx['book'] = Book.objects.get(id=pk)
    return render(request , 'books/book_detail.html' , ctx)


def author_detail(request , pk):
    ctx = {}
    ctx['author'] = Author.objects.get(id=pk)
    return render(request , 'books/author_detail.html' , ctx)

users/views.py
from django.shortcuts import render, redirect
from .models import UserAuthor, Book, Order
from .forms import UserAuthorForm, BookForm


# Create your views here.


def cabinet(request):
    ctx = {}
    ctx['cabinet_tab'] = 'main'
    if request.user.is_authenticated:
        author = UserAuthor.objects.get(user_id=request.user.id)
        form = UserAuthorForm(instance=author)
        if request.method == 'POST':
            form = UserAuthorForm(instance=author, data=request.POST)
            if form.is_valid():
                form.save()
                ctx['saved'] = 1
                form = UserAuthorForm(instance=author)
            else:
                ctx['form'] = form
                ctx['saved'] = 2

        ctx['form'] = form
        return render(request, 'users/cabinet/main.html', ctx)
    else:
        return redirect('users:login')


def all_books(request):
    ctx = {}
    ctx['cabinet_tab'] = 'all_books'
    current_author = UserAuthor.objects.get(user_id=request.user.id)
    all_books = Book.objects.filter(author=current_author)
    ctx['all_books'] = all_books
    return render(request, 'users/cabinet/all_books.html', ctx)


def write_book(request):
    ctx = {}
    ctx['cabinet_tab'] = 'create_book'
    ctx['form'] = BookForm()
    if request.method == 'POST':
        form = BookForm(data=request.POST)
        current_author = UserAuthor.objects.get(user_id=request.user.id)
        if form.is_valid():
            form.save(author=current_author)
    return render(request, 'users/cabinet/write_book.html', ctx)


def books(request):
    ctx = {}
    ctx['all_books'] = Book.objects.all().order_by('-id')
    return render(request, 'users/books.html', ctx)


def search(request):
    ctx = {}
    user_email = request.GET.get('email')
    ctx['email'] = user_email
    all_orders = Order.objects.filter(email=user_email)
    ctx['all_orders'] = all_orders
    return render(request, 'users/search.html', ctx)


def my_order(request):
    ctx = {}
    all_orders = Order.objects.all()
    current_author = UserAuthor.objects.get(user_id=request.user.id)
    list_orders = []
    for order in all_orders:
        all_books = order.books.all()
        if all_books:
            all_books_by_current_author = [book for book in all_books if book.author == current_author]
            if all_books_by_current_author:
                order_obj = {
                    'order': order,
                    'books': all_books_by_current_author
                }
                list_orders.append(order_obj)
    total_sum_books = sum([book.price
                           for order in list_orders
                                for book in order['books']
                           ])
    commision = total_sum_books * 0.05  # percent from platform
    clean_price = total_sum_books - commision
    ctx['cabinet_tab'] = 'my_order'
    ctx['list_orders'] = list_orders
    ctx['commision'] = commision
    ctx['clean_price'] = clean_price
    return render(request, 'users/cabinet/my_order.html', ctx)

templates/users/approve_order.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>approve_order</h1>
<div class="row">
    <div class="col-md-5">
        {% for book in all_books %}
        <div>
            <b>{{book.title}}</b>
            <b>{{book.author.get_name}}</b>
            <b>{{book.price}} грн</b>
        </div>
        {% endfor %}
        <div style="height: 2px; width: 100%; background: black"></div>
        <h3>общая сумма покупки : {{ total_price }} грн</h3>
    </div>

    <div class="col-md-7">
        Вот тут будет форма
        <form action="{% url 'users:approve_order' %}" method="post">
            {% csrf_token %}
            {% for f in form %}
            {{f | as_crispy_field}}
            {% endfor %}
            <button class="btn btn-primary">Потвердить</button>
        </form>
    </div>
</div>
{{all_books}}
{% endblock content %}

templates/users/books.html
{% extends 'index.html' %}

{% block content %}
<h1>книги</h1>

{% for book in all_books %}
<h2>{{book.title}}</h2>
{% if  book.author %}
<p>Автор - {{ book.author.get_name }}</p>
{% else %}
<p>Автор - аноним</p>
{% endif %}
<p>Цена - {{ book.price }} грн / <span class="js-convert" data-id="{{book.id}}" data-grn="{{book.price}}">  </span>
    <img class="spinner-{{book.id}}" width="150"
         src="https://thumbs.gfycat.com/PotableEmbarrassedFrenchbulldog-small.gif" alt="">
</p>
<a href="{% url 'users:add_to_session' book_id=book.id%}" class="btn btn-primary">Добавить в корзину</a>
{% endfor %}
<br>
<input type="number" id="first_number" value="23"> + <input type="number" id="second_number">
<button id="calc">=</button> <span id="output"></span>

{% endblock content %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    // alert('TEST!');
    // confirm('some question?')
    /*
    var name_var_int = 45;
    var name_var_float = 4.6;
    var name_var_str = 'some string!';
    var name_var_list = [1, 2, 3, 4, 5, 'some value', true, false];
    var name_var_dict = {
        'key': 'value',
        'list': [12, 3, 4, 5, 5],
        'some_dict': {
            'a': 1,
            'b': 2,
        }
    };

     */
    // console.log(name_var_int, name_var_float, name_var_str, name_var_list, name_var_dict);
    // var val = prompt('Input some value >>>');
    // console.log(val);

    function name_function(a) {
        if (a == '5') {
            alert('5!!!!!')
        } else if (a == '6') {
            alert('6!!!!!!')
        } else {
            alert('not 5 or 6 !!!!!!')
        }
    }


    var btn = document.getElementById('calc');
    var output = document.getElementById('output');
    btn.addEventListener('click', function () {
        var first_val = document.getElementById('first_number').value;
        var second_val = document.getElementById('second_number').value;
        // alert('click!');
        console.log(first_val);
        console.log(second_val);
        var result = parseInt(first_val) + parseInt(second_val);
        output.innerHTML = result;
    })

    var dollar_buy = 0;
    $.ajax({
        method: 'GET',
        url: 'https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5'
    }).done(function (response) {
        dollar_buy = parseFloat(response[0].buy);
        setTimeout(function () {
            $('.js-convert').map(function (index, elem) {
                var origin_cost = parseFloat($(elem).data('grn'));
                var result_buy_dollar = origin_cost / dollar_buy;
                elem.innerHTML = result_buy_dollar.toFixed(2) + '$';
                $('.spinner-' + $(elem).data('id')).hide();
            })
        }, 2000)

    }).fail(function (errors) {
        console.log(errors);
    })


</script>

{% endblock js %}

templates/users/bucket.html
{% extends 'index.html' %}

{% block content %}
<h1>корзина {{ books |length }}</h1>
<h1>this is code contains in amazun/order branch!</h1>
{% for elem in books %}
    <div>
        <p>{{ elem.title }}</p>
        <p>{{ elem.price }}  грн</p>
        <a href="{% url 'users:delete_from_bucket' elem.id %}" class="btn btn-danger">удалить</a>
    </div>
{% endfor %}
<h2>Общая сумма покупки : {{ sum }} грн</h2>
<a class="btn btn-primary" href="{% url 'users:approve_order' %}"> Потвердить заказ </a>
{% endblock content %}

templates/users/search.html
{% extends 'index.html' %}

{% block content %}

<h1>Все заказы ({{all_orders | length}}) на "{{ email }}" email</h1>

{% for order in all_orders %}
<div>
    <p>price - {{ order.total_price }} грн</p>
    <h4>Books</h4>
    <ul>
        {% for book in order.books.all %}
            <li>{{ book.title }} , {{book.price}}</li>
        {% endfor %}
    </ul>

</div>
{% endfor %}

{% endblock content %}